// traits actions
export const UPDATE_TRAIT = "UPDATE_TRAIT"
export const ADD_TRAIT = "ADD_TRAIT"
export const REMOVE_TRAIT = "REMOVE_TRAIT"

// ui actions
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL" 
export const TOGGLE_SIDE_DRAWER = "TOGGLE_SIDE_DRAWER"
export const TOGGLE_REGISTER_MODAL= "TOGGLE_REGISTER_MODAL"

//auth actions

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

//get characters actions 
export const GET_CHARACTERS = "GET_CHARACTERS"

//character actions

export const UPDATE_NAME = "UPDATE_NAME"
export const UPDATE_CLASS = "UPDATE_CLASS"
export const UPDATE_LEVEL = "UPDATE_LEVEL"
export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME"
export const UPDATE_RACE = "UPDATE_RACE"
export const UPDATE_ALIGNMENT = "UPDATE_ALIGNMENT"
export const UPDATE_EXPERIENCE  = "UPDATE_EXPERIENCE"
export const UPDATE_EXPERIENCE_NEXT_LEVEL = "UPDATE_EXPERIENCE_NEXT_LEVEL" 